"use strict";
const { chromium } = require("playwright");
const fs = require("node:fs/promises");
const http = require("node:http");
const assert = require("node:assert/strict");
const path = require("node:path");
async function main() {
  const dir = await fs.mkdtemp("/tmp/boss-browser-");
  const admin = "browser-test-admin-token-24-characters";
  process.env.DATA_DIR = dir;
  process.env.BOSS_ADMIN_TOKEN = admin;
  process.env.BOSS_SECRET = "browser-test-secret-at-least-32-characters";
  const app = require("../server").server;
  const mock = http.createServer((req, res) => { res.setHeader("Content-Type", "application/json"); res.end(JSON.stringify({ Items: [{ Id: "movie1", Name: "Test Movie", Type: "Movie" }] })); });
  let browser;
  try {
    await new Promise((resolve) => app.listen(0, "0.0.0.0", resolve));
    await new Promise((resolve) => mock.listen(0, "0.0.0.0", resolve));
    browser = await chromium.launch({ executablePath: "/root/.cache/ms-playwright/chromium_headless_shell-1217/chrome-headless-shell-linux64/chrome-headless-shell", headless: true, args: ["--no-sandbox"] });
    const page = await browser.newPage();
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${app.address().port}/bossmedia/admin`);
    await page.waitForSelector(".empty h3");
    await page.fill('[name="adminToken"]', admin);
    await page.fill('[name="addonName"]', "Home cinema");
    await page.fill('[name="baseUrl"]', `http://127.0.0.1:${mock.address().port}`);
    await page.fill('[name="apiKey"]', "test-key");
    await page.click("#probe-btn");
    await page.waitForFunction(() => document.querySelector("#form-output").textContent.includes("Connection successful"));
    await page.click('#addon-form button[type="submit"]');
    await page.waitForSelector(".addon-card");
    await page.waitForSelector("#catalogue-health:not([hidden])");
    assert.equal(await page.locator("#movie-total").isVisible(), true);
    assert.equal(await page.locator("#series-total").isVisible(), true);
    assert.equal(await page.locator("#movie-target, #series-target").count(), 0);
    await page.route("**/api/identity-reviews?*", route => {
      const after = new URL(route.request().url()).searchParams.get("after");
      return route.fulfill({ json: after === "100" ? { reviews: [], next: null } : { reviews: [{ id: 100, title: "Incoming <script> series", sourceName: "Metadata source", type: "series", identities: { imdb: "tt4341500" }, matches: [{ canonicalId: "existing-series", title: "Existing series", year: 2017, identities: { imdb: "tt5669272", tvdb: "294560" }, matchedBy: ["tvdb"] }] }], next: 100 } });
    });
    await page.click("#identity-reviews summary");
    await page.waitForSelector(".identity-review");
    assert.equal(await page.locator(".identity-review h3").textContent(), "Incoming <script> series");
    assert.equal(await page.locator(".identity-review script").count(), 0);
    assert.match(await page.locator(".identity-review").textContent(), /Matched by: tvdb/);
    await page.setViewportSize({ width: 320, height: 900 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: path.resolve("artifacts/identity-review-mobile.png"), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: path.resolve("artifacts/identity-review-desktop.png"), fullPage: true });
    await page.click("#review-next");
    await page.waitForFunction(() => document.querySelector("#review-status").textContent === "No pending reviews");
    await page.click("#review-refresh");
    await page.waitForSelector(".identity-review");
    await page.click("#identity-reviews summary");
    await page.waitForSelector("[data-edit-source]:not([disabled])");
    const sourceInstallUrl = await page.locator("#addon-list .install-url").textContent();
    await page.click("[data-edit-source]");
    assert.equal(await page.inputValue('[name="apiKey"]'), "");
    await page.fill('[name="addonName"]', "Home cinema updated");
    await page.click("#probe-btn");
    await page.waitForFunction(() => document.querySelector("#form-output").textContent.includes("Connection successful"));
    await page.click('#addon-form button[type="submit"]');
    await page.waitForFunction(() => document.querySelector("#addon-list h3")?.textContent === "Home cinema updated");
    assert.equal(await page.locator("#addon-list .install-url").textContent(), sourceInstallUrl);
    await page.selectOption("#output-format", "xtream");
    assert.equal(await page.locator(".credentials dt").count(), 3);
    await page.selectOption("#output-format", "m3u");
    assert.ok((await page.locator(".install-url").textContent()).endsWith("/playlist.m3u"));
    await page.selectOption("#output-format", "boss");
    let polls = 0;
    await page.route("**/api/addons", async (route) => {
      const response = await route.fetch();
      const body = await response.json();
      polls++;
      await route.fulfill({ response, json: { ...body, addons: body.addons.map((addon) => ({ ...addon, syncing: true })) } });
    });
    await page.click("#refresh-btn");
    await page.waitForSelector("#libraries-section", { state: "visible" });
    await page.fill('[name="libraryName"]', "Draft");
    await page.locator('#library-sources input').first().check();
    await page.locator('[name="libraryName"]').focus();
    await page.evaluate(() => document.querySelector('[name="libraryName"]').setSelectionRange(2, 4));
    const beforePolls = polls;
    await page.waitForTimeout(4500);
    assert.ok(polls >= beforePolls + 2, "Exercise two real background sync polls");
    assert.equal(await page.locator('[name="libraryName"]').evaluate((input) => document.activeElement === input && input.selectionStart === 2 && input.selectionEnd === 4), true, "Polling must preserve focus and text selection");
    await page.keyboard.type("XY");
    assert.equal(await page.inputValue('[name="libraryName"]'), "DrXYt");
    await page.locator('#library-sources input').first().focus();
    await page.waitForTimeout(2500);
    assert.equal(await page.locator('#library-sources input').first().evaluate((input) => document.activeElement === input && input.checked), true, "Polling must preserve source selection and keyboard focus");
    await page.unroute("**/api/addons");
    await page.fill('[name="libraryName"]', "All authorized media");
    await page.locator('#library-sources input').first().check();
    await page.click('#library-form button[type="submit"]');
    await page.waitForSelector("#library-list .addon-card");
    assert.ok((await page.locator("#library-list .install-url").textContent()).endsWith("/addon.boss"));
    const installUrl = await page.locator("#library-list .install-url").textContent();
    await page.click("[data-edit-library]");
    await page.fill('[name="libraryName"]', "Family library");
    await page.selectOption('[name="codecs"]', "h264");
    await page.selectOption('[name="maxHeight"]', "1080");
    await page.selectOption('[name="language"]', "en");
    await page.locator('[name="hdr"]').uncheck();
    await page.locator('[name="strictCapabilities"]').check();
    await page.click('#library-form button[type="submit"]');
    await page.waitForFunction(() => document.querySelector("#library-list h3")?.textContent === "Family library");
    assert.equal(await page.locator("#library-list .install-url").textContent(), installUrl);
    await page.click("[data-edit-library]");
    assert.equal(await page.inputValue('[name="codecs"]'), "h264");
    assert.equal(await page.inputValue('[name="maxHeight"]'), "1080");
    assert.equal(await page.locator('[name="hdr"]').isChecked(), false);
    assert.equal(await page.locator('[name="strictCapabilities"]').isChecked(), true);
    await page.fill('[name="libraryName"]', "Unsaved change");
    await page.click("#cancel-library-edit");
    assert.equal(await page.locator("#library-list h3").textContent(), "Family library");
    await fs.mkdir(path.join(__dirname, "../artifacts"), { recursive: true });
    for (const [name, width, height] of [["desktop", 1440, 1000], ["mobile", 390, 844], ["small-mobile", 320, 720]]) {
      await page.setViewportSize({ width, height });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${name}: horizontal overflow`);
      assert.ok(await page.locator(".brand img").evaluate((img) => img.complete && img.naturalWidth > 0));
      assert.ok(await page.locator("svg.lucide").count() > 5);
      await page.screenshot({ path: path.join(__dirname, `../artifacts/${name}.png`), fullPage: true });
      await page.selectOption("#output-format", "xtream");
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
      await page.screenshot({ path: path.join(__dirname, `../artifacts/${name}-xtream.png`), fullPage: true });
      await page.selectOption("#output-format", "boss");
    }
    await page.locator('[name="sourceType"][value="webdav"]').check({ force: true });
    assert.equal(await page.locator('#addon-form [name="username"]').isVisible(), true);
    await page.locator('[name="sourceType"][value="other"]').check({ force: true });
    assert.equal(await page.locator("#url-label").textContent(), "Source addon URL");
    await page.locator('[name="sourceType"][value="catalogue"]').check({ force: true });
    assert.equal(await page.locator("#url-label").textContent(), "Source addon URL");
    await page.click("#addon-list [data-delete]");
    await page.click("#confirm-delete");
    await page.waitForFunction(() => document.querySelector("#addon-list").textContent.includes("No addons yet"));
    await page.click("#lock-btn");
    assert.equal(await page.inputValue('[name="adminToken"]'), "");
    await page.goto(`http://127.0.0.1:${app.address().port}/bossmedia/sdk`);
    assert.equal(await page.locator("h1").textContent(), "BossTunnel App SDK");
    for (const [name, width, height] of [["desktop", 1440, 1000], ["mobile", 390, 844], ["small-mobile", 320, 720]]) {
      await page.setViewportSize({ width, height });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `SDK ${name}: horizontal overflow`);
      assert.ok(await page.locator(".brand img").evaluate((img) => img.complete && img.naturalWidth > 0));
      await page.screenshot({ path: path.join(__dirname, `../artifacts/sdk-${name}.png`), fullPage: true });
    }
    await page.goto(`http://127.0.0.1:${app.address().port}/bossmedia/sdk/addons`);
    for (const [name, width, height] of [["desktop", 1440, 1000], ["mobile", 390, 844], ["small-mobile", 320, 720]]) {
      await page.setViewportSize({ width, height });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `Author SDK ${name}: horizontal overflow`);
      await page.screenshot({ path: path.join(__dirname, `../artifacts/addon-sdk-${name}.png`), fullPage: true });
    }
    assert.deepEqual(errors, []);
    console.log("Browser checks passed: create, probe, remove, lock, source controls, desktop/mobile layout, icons and logo.");
  } finally {
    if (browser) await browser.close();
    app.closeAllConnections(); mock.closeAllConnections();
    await Promise.all([new Promise((resolve) => app.close(resolve)), new Promise((resolve) => mock.close(resolve))]);
    await require("../server").close();
    await fs.rm(dir, { recursive: true, force: true });
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
